#pragma once 
// Sounds
#define SOUND_SFX_DASH                                  "Efectos/MovementSounds/Dash"
    //Enemies
#define SOUND_SFX_ENEMYDAMAGED                          "Efectos/EnemySounds/Enemy_Damaged"
#define SOUND_SFX_ENEMYATTACK                           "Efectos/EnemySounds/Enemy_Attack"
#define SOUND_SFX_ENEMYDEATH                            "Efectos/EnemySounds/Enemy_Death"
#define SOUND_SFX_ENEMYAGGRO                            "Efectos/EnemySounds/Enemy_Aggro"
#define SOUND_SFX_ENEMYHIT                              "Efectos/EnemySounds/Player_Hit"
    //Vending
#define SOUND_SFX_CARD_SUCCESS                          "Efectos/InteractionSounds/Full_Card_Lecture_Success_Door"
#define SOUND_SFX_CARD_FAIL                             "Efectos/InteractionSounds/Full_Card_Lecture_Fail"
#define SOUND_SFX_NEGATIVE_INTERACTION                  "Efectos/InteractionSounds/Negative_Interaction"
#define SOUND_SFX_DOOR_OPEN                             "Efectos/InteractionSounds/Door_Open"
#define SOUND_SFX_PICKUP_WEAPON                         "Efectos/InteractionSounds/Pickup_Weapon"
#define SOUND_SFX_PICKUP_AMMO                           "Efectos/InteractionSounds/Pickup_Ammo"
#define SOUND_SFX_PICKUP_HEAL                           "Efectos/InteractionSounds/Pickup_Heal"
#define SOUND_SFX_VENDING_MACHINE                       "Efectos/InteractionSounds/Vending_Machine"
    //WEAPON
#define SOUND_SFX_WEAPON_NOAMMO                         "Efectos/WeaponSounds/No_Ammo_Shoot"
#define SOUND_SFX_WEAPON_HANDGUN                        "Efectos/WeaponSounds/HandGun_Shoot_Metal"
#define SOUND_SFX_WEAPON_SHOTGUN                        "Efectos/WeaponSounds/Shotgun_shoot"
#define SOUND_SFX_WEAPON_MACHINEGUN                     "Efectos/WeaponSounds/MachineGun"
#define SOUND_SFX_WEAPON_MACHINEGUN_SHOOT                "Efectos/WeaponSounds/MachineGun_Shoot"
#define SOUND_SFX_WEAPON_SNIPER                         "Efectos/WeaponSounds/Sniper_Charge_Shoot"
#define SOUND_SFX_WEAPON_SEMIAUTOMATIC                  "Efectos/WeaponSounds/Semiautomatic_Shoot"
#define SOUND_SFX_WEAPON_CANNON                         "Efectos/WeaponSounds/Retroman_Cannon" 
#define SOUND_SFX_WEAPON_CANNON_BULLET                  "" //PlaceHolder
#define SOUND_SFX_WEAPON_EXPLOSIVE                      "Efectos/WeaponSounds/Explosion_Launch" 
#define SOUND_SFX_WEAPON_EXPLOSIVE_BULLET               "Efectos/WeaponSounds/Explosion_Flying" 
#define SOUND_SFX_WEAPON_EXPLOSIVE_BULLET_EXPLOSION     "Efectos/WeaponSounds/Explosion_Explosion"
#define SOUND_SFX_WEAPON_ENEMY_SHOOT                    "Efectos/EnemySounds/Enemy_Shoot"
    //VFX WEAPON
    #define SOUND_VFX_LIAM_PICKUP_HANDGUN               "Voces/MainCharacter/Liam_Pickup_Handgun"
    #define SOUND_VFX_LIAM_PICKUP_SEMIAUTO              "Voces/MainCharacter/Liam_Pickup_Semiauto"
    #define SOUND_VFX_LIAM_PICKUP_SHOTGUN               "Voces/MainCharacter/Liam_Pickup_Shotgun"
    #define SOUND_VFX_LIAM_PICKUP_MACHINEGUN            "Voces/MainCharacter/Liam_Pickup_Machinegun"
    #define SOUND_VFX_LIAM_PICKUP_SNIPER                "Voces/MainCharacter/Liam_Pickup_Sniper"
    #define SOUND_VFX_LIAM_PICKUP_EXPLOSIVE             ""
    #define SOUND_VFX_LIAM_PICKUP_CANNON                ""
    //VFX
#define SOUND_VFX_LIAM_PICKUP_CARD                      "Voces/MainCharacter/Liam_Pickup_Card"
#define SOUND_VFX_LIAM_SUCCESS_POINT_DOOR               "Voces/MainCharacter/Liam_Interaction_Success_Point_Door"
#define SOUND_VFX_LIAM_FAIL_POINT_DOOR                  "Voces/MainCharacter/Liam_Interaction_Fail_Point_Door"
#define SOUND_VFX_LIAM_PICKUP_HEAL                      "Voces/MainCharacter/Liam_Pickup_Heal"
#define SOUND_VFX_LIAM_PICKUP_AMMO                      "Voces/MainCharacter/Liam_Pickup_Ammo"
#define SOUND_VFX_LIAM_FAIL_CARD_DOOR                   "Voces/MainCharacter/Liam_Interaction_Fail_Card_Door"
#define SOUND_VFX_RAID_START                            "Efectos/EnemySounds/Enemy_Angry_Sounds"
// Music
#define SOUND_MUSIC_AMBIENCE_INGAME_1                   "Música/Ambience1"
#define SOUND_MUSIC_AMBIENCE_INGAME_2                   "Música/Ambience2"
#define SOUND_MUSIC_AMBIENCE_INGAME_3                   "Música/Ambience3"
#define SOUND_MUSIC_MAIN_MENU                           "Música/MainMenuV2"
    // Parameters
#define SOUND_PARAM_DANGERLEVEL                         "DangerLevel"
#define SOUND_PARAM_PAN3D                               "PanLevel"

// Models
    // Characters
#define MODEL_CHARAC_LIAM                               "assets/characters/Liam.obj"
#define MODEL_CHARAC_HANS                               "assets/characters/Hans.obj"
#define MODEL_CHARAC_ENEMY_MELEE                        "assets/characters/melee/"
#define MODEL_CHARAC_ENEMY_SHOOTER                      "assets/characters/ranged/"
#define MODEL_CHARAC_ENEMY_KAMIKAZE                     "assets/characters/detonator/"
#define MODEL_CHARAC_ENEMY_DUMMY                        "assets/characters/dummy.obj"
    // Weapons
#define MODEL_WEAPON_HANDGUN                            "assets/weapons/finalgun.obj"
#define MODEL_WEAPON_SHOTGUN                            "assets/weapons/shotgun.obj"
#define MODEL_WEAPON_MACHINEGUN                         "assets/weapons/HA_funador_pesado.obj"
#define MODEL_WEAPON_SEMIAUTOMATIC                      "assets/weapons/semiautomatic-rifle.obj"
#define MODEL_WEAPON_SNIPER                             "assets/weapons/francotirador.obj"
#define MODEL_WEAPON_EXPLOSIVE                          "assets/weapons/missile-launcher.obj"
#define MODEL_WEAPON_EXPLOSIVE_BULLET                   "assets/weapons/missile.obj" 
#define MODEL_WEAPON_CANNON                             "assets/weapons/retroman.obj"
#define MODEL_WEAPON_CANNON_BULLET                      "assets/weapons/plasmaball.obj"
    // Objects
#define MODEL_OBJECT_AMMO_VENDING_MACHINE               "assets/objects/AmmoMachine.obj"
#define MODEL_OBJECT_HEAL_VENDING_MACHINE               "assets/objects/MachineHeal.obj"
#define MODEL_OBJECT_AMMO_PAD                           "assets/objects/AmmoMachinePad.obj"
#define MODEL_OBJECT_HEAL_PAD                           "assets/objects/MachineHealPad.obj"
#define MODEL_OBJECT_AMMO_KIT                           "assets/objects/pickupAmmo.obj"
#define MODEL_OBJECT_HEAL_KIT                           "assets/objects/healkit.obj"
#define MODEL_OBJECT_DOOR                               "assets/objects/frameless-door/"
#define MODEL_OBJECT_DOOR_CARD                          "assets/objects/frameless-door-locked/"
#define MODEL_OBJECT_CARD                               "assets/objects/card_Lucas.obj"
#define MODEL_OBJECT_CARD_LECTOR                        "assets/objects/cardlector.obj"
    // Default
#define MODEL_DEFAULT_CUBE                              "assets/objects/defaultCube.obj"
#define MODEL_DEFAULT_NOANIM                            "noanim.obj"

// Assets 2D
#define ASSET_HUD_DEFAULT_RECT                          "assets/default_rect.png"
#define ASSET_MENU_FAVICON                              "assets/favicon.jpg"
#define ASSET_SKYBOX_BLUE_FOLDER                        "assets/skybox/"
#define ASSET_SKYBOX_ULTRAHIGH_FOLDER                   "ultrahigh/"
#define ASSET_SKYBOX_HIGH_FOLDER                        "high/"
#define ASSET_SKYBOX_MID_FOLDER                         "mid/"
#define ASSET_SKYBOX_LOW_FOLDER                         "low/"
#define ASSET_SKYBOX_TOP                                "top.png"
#define ASSET_SKYBOX_BOT                                "bot.png"
#define ASSET_SKYBOX_LEFT                               "left.png"
#define ASSET_SKYBOX_RIGHT                              "right.png"
#define ASSET_SKYBOX_FRONT                              "front.png"
#define ASSET_SKYBOX_BACK                               "back.png"

// Fonts


// Config
#define UTIL_CONFIG_FILE                                "data/config.json"
#define UTIL_SAVE_FILE                                  "data/save.json"
#define UTIL_MAP_MODEL_FOLDER                           "assets/maps/"
#define UTIL_MAP_DATA_FOLDER                            "data/mapdata/"
#define UTIL_MAP_ORDER_FILE                             "mapOrder.json"
#define UTIL_HUDOVERLAY_GAME_BLUE                       "data/overlay/game_blue.json"
#define UTIL_HUDOVERLAY_GAME_GREEN                      "data/overlay/game_green.json"
#define UTIL_HUDOVERLAY_MAIN_MENU                       "data/overlay/main_menu.json"
#define UTIL_HUDOVERLAY_PAUSE_MENU                      "data/overlay/pause_menu.json"
#define UTIL_HUDOVERLAY_ONLINE_SETUP                    "data/overlay/online_setup.json"
#define UTIL_HUDOVERLAY_SETTINGS                        "data/overlay/settings.json"
#define UTIL_HUDOVERLAY_CODEX_MAIN                      "data/overlay/codex_main.json"
#define UTIL_HUDOVERLAY_CODEX_SECTION                   "data/overlay/codex_section.json"
#define UTIL_HUDOVERLAY_CODEX_PAGE                      "data/overlay/codex_page.json"
#define UTIL_HUDOVERLAY_CREDITS                         "data/overlay/credits.json"
#define UTIL_HUDOVERLAY_LEVEL_SELECTION                 "data/overlay/level_selection.json"
#define UTIL_HUDOVERLAY_LOADING_SCREEN                  "data/overlay/loading_screen.json"
#define UTIL_HUDOVERLAY_SELECTION_LEVELFINISHED         "data/overlay/selection_level_finished.json"
#define UTIL_HUDOVERLAY_SELECTION_EXITGAME              "data/overlay/selection_exit_game.json"
#define UTIL_HUDOVERLAY_SELECTION_DISCONNECTED          "data/overlay/selection_disconnected.json"
#define UTIL_HUDOVERLAY_SELECTION_EXITONLINE            "data/overlay/selection_exit_online.json"
